<?php
/**
 * @file
 * Platform.sh API module.
 */

/**
 * Implements hook_entity_info().
 */
function platformsh_api_entity_info() {
  $items = array();
  $items['platformsh_api_subscription'] = array(
    'label' => t('Platform.sh Subscription'),
    'controller class' => 'PlatformshApiSubscriptionController',
    'entity class' => 'PlatformshApiSubscription',
    'base table' => 'platformsh_api_subscription',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'subscription_id',
      'label' => 'external_id',
      'bundle' => 'type',
    ),
    'module' => 'platformsh_api',
    'access callback' => 'platformsh_api_subscription_access',
    'metadata controller class' => 'PlatformshApiSubscriptionMetadataController',
    'views controller class' => 'EntityDefaultViewsController',
  );

  return $items;
}

/**
 * Entity access callback for a subscription.
 */
function platformsh_api_subscription_access($op, PlatformshApiSubscription $subscription = NULL, $account = NULL) {
  return user_access('administer platform.sh integration', $account);
}

/**
 * Implements hook_menu().
 */
function platformsh_api_menu() {
  $items = array();
  $items['admin/config/services/platform-sh'] = array(
    'title' => 'Platform.sh',
    'description' => 'Administer Platform.sh API integration.',
    'access arguments' => array('administer platform.sh integration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('platformsh_api_config_form'),
    'file' => 'includes/platformsh_api.pages.inc',
  );
  $items['admin/structure/platform-sh/subscriptions'] = array(
    'title' => 'Platform.sh subscriptions',
    'description' => 'List Platform.sh subscriptions.',
    'access callback' => 'platformsh_api_subscription_access',
    'access arguments' => array('view'),
    'page callback' => 'platformsh_api_list_subscriptions',
    'file' => 'includes/platformsh_api.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function platformsh_api_permission() {
  return array(
    'administer platform.sh integration' => array(
      'title' => t('Administer Platform.sh integration'),
    ),
  );
}

/**
 * Form to refresh subscriptions.
 */
function platformsh_api_refresh_subscriptions_form($form, &$form_state) {
  $form['refresh'] = array(
    '#type' => 'submit',
    '#value' => t('Refresh subscriptions'),
  );
  return $form;
}

/**
 * Refresh subscriptions form - submit callback.
 */
function platformsh_api_refresh_subscriptions_form_submit(&$form, &$form_state) {
  platformsh_api_refresh_subscriptions();
}

/**
 * Get a client object.
 *
 * @param string $api_token
 *   An API token. Defaults to the token set in the variable
 *   'platformsh_api_token'.
 *
 * @return \Platformsh\Client\PlatformClient
 *   A Platform.sh API client object.
 */
function platformsh_api_client($api_token = NULL) {
  static $client;
  if (!isset($client) || isset($api_token)) {
    $connector = new \Platformsh\Client\Connection\Connector(array(
      'api_token' => variable_get('platformsh_api_token', $api_token),
    ));

    $client = new \Platformsh\Client\PlatformClient($connector);
  }

  return $client;
}

/**
 * Handle an exception from a bad API response.
 *
 * @param Exception $e
 *   The Guzzle response exception.
 */
function platformsh_api_handle_exception(Exception $e) {
  $settings_url = url('admin/config/services/platform-sh');
  $params = array(
    '@settings' => $settings_url,
  );

  if ($e instanceof \GuzzleHttp\Exception\BadResponseException) {
    $response = $e->getResponse();
    if ($response && $response->getStatusCode() === 401) {
      drupal_set_message(
        t('Unauthorized. Your Platform.sh <a href="@settings">API token</a> is probably invalid.', $params),
        'error'
      );
      return;
    }
  }
  elseif ($e instanceof RuntimeException && $e->getMessage() === 'Not logged in') {
    drupal_set_message(
      t('You need to set your Platform.sh <a href="@settings">API token</a>.', $params),
      'error'
    );
    return;
  }

  throw $e;
}

/**
 * Validate an API token.
 *
 * @param string $api_token
 *   The API token to validate.
 *
 * @return bool
 *   TRUE if the API token is valid, FALSE otherwise.
 */
function platformsh_api_validate_token($api_token) {
  if (empty($api_token)) {
    throw new \InvalidArgumentException('Empty API token');
  }

  $client = platformsh_api_client($api_token);
  try {
    $client->getAccountInfo();
  }
  catch (\GuzzleHttp\Exception\BadResponseException $e) {
    if ($e->getResponse() && $e->getResponse()->getStatusCode() === 401) {
      return FALSE;
    }
    throw $e;
  }

  return TRUE;
}

/**
 * Refresh the internally saved subscriptions.
 */
function platformsh_api_refresh_subscriptions() {
  $client = platformsh_api_client();
  try {
    $subscriptions = $client->getSubscriptions();
  }
  catch (Exception $e) {
    platformsh_api_handle_exception($e);
    $subscriptions = array();
  }

  foreach ($subscriptions as $subscription) {
    platformsh_api_save_subscription($subscription);
  }
}

/**
 * Save a subscription as an internal entity.
 *
 * @param \Platformsh\Client\Model\Subscription $source
 *   The subscription object from the API client.
 * @param object                                $account
 *   The Drupal user account object to associate with the subscription
 *   (optional).
 *
 * @return bool
 *   TRUE on success, FALSE otherwise.
 */
function platformsh_api_save_subscription(\Platformsh\Client\Model\Subscription $source, $account = NULL) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'platformsh_api_subscription');
  $query->propertyCondition('external_id', $source->id);
  $result = $query->execute();

  // Updating an existing subscription.
  if (!empty($result['platformsh_api_subscription'])) {
    $subscription = entity_load_single('platformsh_api_subscription', key($result['platformsh_api_subscription']));

    $original = clone $subscription;
    $subscription->uid = $account ? $account->uid : NULL;
    $subscription->url = $source->getUri();
    $subscription->data = $source->getData();

    // Don't do anything if the subscription has not changed.
    if ($original === $subscription) {
      return TRUE;
    }
  }
  else {
    // Saving a new subscription.
    $values = array(
      'uid' => $account ? $account->uid : NULL,
      'external_id' => $source->id,
      'type' => 'platformsh_project',
      'url' => $source->getUri(),
      'data' => $source->getData(),
    );
    $subscription = entity_create('platformsh_api_subscription', $values);
  }

  return $subscription->save();
}

/**
 * Implements hook_views_api().
 */
function platformsh_api_views_api() {
  return array('api' => 3);
}

/**
 * @param \PlatformshApiSubscription $subscription
 *
 * @return string
 */
function platformsh_api_subscription_project_link_getter(PlatformshApiSubscription $subscription) {
  $data = $subscription->data;
  if (empty($data['project_ui'])) {
    return NULL;
  }

  $title = empty($data['project_title']) ? $data['project_id'] : $data['project_title'];
  return l($title, $data['project_ui']);
}
