<?php
/**
 * @file
 * Platform.sh API Commerce integration module.
 */

/**
 * Implements hook_menu().
 */
function platformsh_api_commerce_menu() {
  $items = array();

  // @todo when https://www.drupal.org/node/2458657 is committed, use %commerce_license
  $items['platformsh/activation-callback/%'] = array(
    'title' => 'Subscription activation callback',
    'page callback' => 'platformsh_api_commerce_activation_callback',
    'page arguments' => array(2),
    'access callback' => 'platformsh_api_commerce_activation_callback_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'includes/platformsh_api_commerce.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function platformsh_api_commerce_ctools_plugin_directory($module, $plugin) {
  if ($module == 'commerce_license') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_field_access().
 */
function platformsh_api_commerce_field_access($op, $field, $entity_type, $entity, $account) {
  // Prevent access to edit the subscription reference field in the UI.
  if ($entity_type == 'commerce_license' && $field['field_name'] == 'platformsh_license_subscription') {
    return FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function platformsh_api_commerce_form_platformsh_api_config_form_alter(&$form, &$form_state) {
  $form['commerce'] = array(
    '#type' => 'fieldset',
    '#title' => t('Commerce integration'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['commerce']['platformsh_api_commerce_wait'] = array(
    '#type' => 'checkbox',
    '#title' => t('Wait for activation'),
    '#description' => t('Wait for the subscription to become active during the initial synchronization.'),
    '#default_value' => variable_get('platformsh_api_commerce_wait', TRUE),
  );
  $form['commerce']['platformsh_api_commerce_use_callback'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use activation callback'),
    '#default_value' => variable_get('platformsh_api_commerce_use_callback', TRUE),
    '#description' => t('Request a notification from Platform.sh after activation.'),
  );
}

/**
 * Check access for the subscription activation callback.
 *
 * @param int $license_id
 *   The subscription license entity ID.
 *
 * @return bool
 *   TRUE if access is granted, FALSE if denied.
 */
function platformsh_api_commerce_activation_callback_access($license_id) {
  $license = entity_load_single('commerce_license', $license_id);
  if (!$license instanceof \PlatformshApiCommerceSubscriptionLicense) {
    return FALSE;
  }

  return isset($_GET['token']) && platformsh_api_commerce_validate_token($_GET['token'], $license);
}

/**
 * Generate a token to validate the activation callback.
 *
 * @param \CommerceLicenseBase $license
 *   The subscription license entity.
 *
 * @return string
 *   A token.
 */
function platformsh_api_commerce_get_token(\CommerceLicenseBase $license) {
  $data = serialize(array($license->license_id, $license->uid));
  $key = drupal_get_private_key() . '-' . drupal_get_hash_salt();
  return drupal_hmac_base64($data, $key);
}

/**
 * Validate a token in the activation callback.
 *
 * @param string $token
 *   A token passed in the activation callback.
 * @param \CommerceLicenseBase $license
 *   The subscription license entity.
 *
 * @return bool
 *   TRUE if valid, FALSE otherwise.
 */
function platformsh_api_commerce_validate_token($token, \CommerceLicenseBase $license) {
  return $token === platformsh_api_commerce_get_token($license);
}

/**
 * Get the activation callback URL.
 *
 * @param \CommerceLicenseBase $license
 *   The subscription license entity.
 *
 * @return string
 *   The absolute URL to the activation callback.
 */
function platformsh_api_commerce_get_activation_callback(\CommerceLicenseBase $license) {
  return url(
    'platformsh/activation-callback/' . $license->license_id,
    array(
      'absolute' => TRUE,
      'query' => array(
        'token' => platformsh_api_commerce_get_token($license),
      ),
    )
  );
}
